//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDA_ARS.Umbraco.App_Plugins.UsdaDataImporter {
    
    
    public partial class upload_file {
    }
}
